name := "invertedIndex"
version := "1.0.0"
scalaVersion := "2.10.4"
libraryDependencies += "org.apache.spark" %% "spark-core" % "1.3.1"
resolvers += "Akka Respository" at "http://repo.akka.io/releases/"
